services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_ledger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/car_ledger_db
      BIND_ADDRESS: backend:8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      BACKEND_URL: http://127.0.0.1:8081
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data: